apiRules:
- include:
    hasAttribute:
      uid: FrameworkSystems.FrameworkExceptions.DocfxBrowsableAttribute
    type: Type
- include:
    hasAttribute:
      uid: FrameworkSystems.FrameworkExceptions.DocfxBrowsableAttribute
    type: Member

- exclude:
    type: Type
- exclude:
    type: Member
